// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240115042931_hh")]
    partial class hh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Entities.Content.BlogComment", b =>
                {
                    b.Property<Guid>("idBlogComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogidBlog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idBlog")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogComment");

                    b.HasIndex("BlogidBlog");

                    b.ToTable("BlogComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.BlogReply", b =>
                {
                    b.Property<Guid>("idBlogReply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogCommentidBlogComment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idBlogComment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogReply");

                    b.HasIndex("BlogCommentidBlogComment");

                    b.ToTable("BlogReplies");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.Blogs", b =>
                {
                    b.Property<Guid>("idBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("idBlog");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.PostComment", b =>
                {
                    b.Property<Guid>("idPostComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostidPost")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idPost")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idPostComment");

                    b.HasIndex("PostidPost");

                    b.ToTable("PostComment");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.PostReply", b =>
                {
                    b.Property<Guid>("idPostReply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostCommentidPostComment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idPostComment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idPostReply");

                    b.HasIndex("PostCommentidPostComment");

                    b.ToTable("PostReply");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.Posts", b =>
                {
                    b.Property<Guid>("idPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectidProject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.Property<Guid>("idProject")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idPost");

                    b.HasIndex("ProjectidProject");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Projects.ProjectInfo", b =>
                {
                    b.Property<Guid>("idProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("process")
                        .HasColumnType("int");

                    b.Property<int>("visibility")
                        .HasColumnType("int");

                    b.HasKey("idProject");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Projects.ProjectInvitation", b =>
                {
                    b.Property<Guid>("idProjectInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectidProject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("confirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("idAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("idProject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isAccept")
                        .HasColumnType("bit");

                    b.HasKey("idProjectInvitation");

                    b.HasIndex("ProjectidProject");

                    b.ToTable("ProjectInvitation");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("idProjectMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectidProject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("confirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("idAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("idProject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isAcept")
                        .HasColumnType("bit");

                    b.Property<bool>("isManager")
                        .HasColumnType("bit");

                    b.HasKey("idProjectMember");

                    b.HasIndex("ProjectidProject");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.BlogComment", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Content.Blogs", "Blog")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogidBlog");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.BlogReply", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Content.BlogComment", "BlogComment")
                        .WithMany("Replies")
                        .HasForeignKey("BlogCommentidBlogComment");

                    b.Navigation("BlogComment");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.PostComment", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Content.Posts", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostidPost");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.PostReply", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Content.PostComment", "PostComment")
                        .WithMany("PostReplies")
                        .HasForeignKey("PostCommentidPostComment");

                    b.Navigation("PostComment");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.Posts", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Projects.ProjectInfo", "Project")
                        .WithMany("Posts")
                        .HasForeignKey("ProjectidProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Projects.ProjectInvitation", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Projects.ProjectInfo", "Project")
                        .WithMany("ProjectInvitations")
                        .HasForeignKey("ProjectidProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Projects.ProjectMember", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Projects.ProjectInfo", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectidProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.BlogComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.Blogs", b =>
                {
                    b.Navigation("BlogComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.PostComment", b =>
                {
                    b.Navigation("PostReplies");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Content.Posts", b =>
                {
                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Projects.ProjectInfo", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("ProjectInvitations");

                    b.Navigation("ProjectMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
