// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogComment", b =>
                {
                    b.Property<Guid>("idBlogComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogsidBlog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("idBlog")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogComment");

                    b.HasIndex("BlogsidBlog");

                    b.ToTable("BlogComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogCommentLike", b =>
                {
                    b.Property<Guid>("idBlogCommentLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogCommentidBlogComment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("idBlogComment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogCommentLike");

                    b.HasIndex("BlogCommentidBlogComment");

                    b.ToTable("BlogCommentLikes");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogImage", b =>
                {
                    b.Property<Guid>("idBlogImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogsidBlog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("idBlog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idBlogImage");

                    b.HasIndex("BlogsidBlog");

                    b.ToTable("BlogImages");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogLike", b =>
                {
                    b.Property<Guid>("idBlogLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogidBlog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("idBlog")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogLike");

                    b.HasIndex("BlogidBlog");

                    b.ToTable("BlogLikes");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogReply", b =>
                {
                    b.Property<Guid>("idBlogReply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogCommentidBlogComment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("idBlogComment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogReply");

                    b.HasIndex("BlogCommentidBlogComment");

                    b.ToTable("BlogReplies");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogReplyLike", b =>
                {
                    b.Property<Guid>("idBlogReplyLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogReplyidBlogReply")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("idBlogReply")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idBlogReplyLike");

                    b.HasIndex("BlogReplyidBlogReply");

                    b.ToTable("BlogReplyLikes");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.Blogs", b =>
                {
                    b.Property<Guid>("idBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("idBlog");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogComment", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Blog.Blogs", "Blogs")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogsidBlog");

                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogCommentLike", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Blog.BlogComment", "BlogComment")
                        .WithMany("BlogCommentLikes")
                        .HasForeignKey("BlogCommentidBlogComment");

                    b.Navigation("BlogComment");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogImage", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Blog.Blogs", "Blogs")
                        .WithMany()
                        .HasForeignKey("BlogsidBlog");

                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogLike", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Blog.Blogs", "Blog")
                        .WithMany("BlogLikes")
                        .HasForeignKey("BlogidBlog");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogReply", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Blog.BlogComment", "BlogComment")
                        .WithMany("BlogReplies")
                        .HasForeignKey("BlogCommentidBlogComment");

                    b.Navigation("BlogComment");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogReplyLike", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Blog.BlogReply", "BlogReply")
                        .WithMany("BlogReplyLikes")
                        .HasForeignKey("BlogReplyidBlogReply");

                    b.Navigation("BlogReply");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogComment", b =>
                {
                    b.Navigation("BlogCommentLikes");

                    b.Navigation("BlogReplies");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.BlogReply", b =>
                {
                    b.Navigation("BlogReplyLikes");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Blog.Blogs", b =>
                {
                    b.Navigation("BlogComments");

                    b.Navigation("BlogLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
